<?php

namespace Application\CotisationBundle\Repository;

/**
 * YearCotisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearCotisationRepository extends \Doctrine\ORM\EntityRepository
{
}
