<?php

namespace Application\OffreBundle\Repository;

/**
 * FileOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
