<?php

namespace Admin\ImportBundle\Repository;

/**
 * UserImportLineStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImportLineStateRepository extends \Doctrine\ORM\EntityRepository
{
}
