<?php

namespace Admin\ImportBundle\Repository;

/**
 * UserImportLineErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImportLineErrorRepository extends \Doctrine\ORM\EntityRepository
{
    public function clean()
    {
       return $this->getEntityManager()->createQuery(
           'DELETE FROM AdminImportBundle:UserImportLineError u WHERE u.id NOT IN (SELECT DISTINCT IDENTITY(u2.errors) from AdminImportBundle:UserImportLine u2)'
       )->execute();
    }
}
