<?php

namespace Admin\ImportBundle\Repository;

/**
 * UserImportActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImportActionRepository extends \Doctrine\ORM\EntityRepository
{
}
