<?php

namespace Admin\ImportBundle\Repository;

/**
 * UserImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImportRepository extends \Doctrine\ORM\EntityRepository
{
}
