<?php

namespace Admin\ImportBundle\Repository;

/**
 * UserImportLineErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImportLineErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
