<?php

namespace Admin\ImportBundle\Repository;

/**
 * UserImportStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImportStateRepository extends \Doctrine\ORM\EntityRepository
{
}
