<?php

namespace Admin\ImportBundle\Repository;

/**
 * UserImportLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImportLineRepository extends \Doctrine\ORM\EntityRepository
{
}
